# Generated by Django 3.0.8 on 2020-07-09 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('categoria', models.CharField(choices=[('riester', 'Masculino'), ('genericos', 'Femenino'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCION')),
                ('stockinicial', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('por', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('final', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('veces', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='BODEGAS', verbose_name='IMAGEN')),
                ('autor', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodegas',
                'verbose_name_plural': 'Bodegass',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Bodegas')),
            ],
            options={
                'verbose_name': 'Salidas',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='Bodegariester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=450, verbose_name='NOMBRE')),
                ('categoria', models.CharField(choices=[('riester', 'Masculino'), ('genericos', 'Femenino'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCION')),
                ('stockinicial', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('por', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('final', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('veces', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='BODEGASRIESTER', verbose_name='IMAGEN')),
                ('autor', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodegariester',
                'verbose_name_plural': 'Bodegariesters',
            },
        ),
        migrations.CreateModel(
            name='Bodegaotrasmarcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=450, verbose_name='NOMBRE')),
                ('categoria', models.CharField(choices=[('riester', 'Masculino'), ('genericos', 'Femenino'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCION')),
                ('stockinicial', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('por', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('final', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('veces', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='BODEGASOTRASMARCAS', verbose_name='IMAGEN')),
                ('autor', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodegaotrasmarcas',
                'verbose_name_plural': 'Bodegaotrasmarcass',
            },
        ),
        migrations.CreateModel(
            name='Bodegagenericos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=450, verbose_name='NOMBRE')),
                ('categoria', models.CharField(choices=[('riester', 'Masculino'), ('genericos', 'Femenino'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='DESCRIPCION')),
                ('stockinicial', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('salidas', models.IntegerField(default=0)),
                ('por', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('final', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('veces', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='BODEGASGENERICOS', verbose_name='IMAGEN')),
                ('autor', models.ForeignKey(blank=True, max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodegagenericos',
                'verbose_name_plural': 'Bodegagenericoss',
            },
        ),
    ]
