# Generated by Django 3.0.8 on 2020-07-09 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegagenericos',
            options={'verbose_name': 'Bodega generico', 'verbose_name_plural': 'Bodega genericos'},
        ),
        migrations.AlterModelOptions(
            name='bodegaotrasmarcas',
            options={'verbose_name': 'Bodega otras marcas', 'verbose_name_plural': 'Bodega otras marcas'},
        ),
        migrations.AlterModelOptions(
            name='bodegariester',
            options={'verbose_name': 'Bodega riester', 'verbose_name_plural': 'Bodega riester'},
        ),
        migrations.AlterModelOptions(
            name='bodegas',
            options={'verbose_name': 'Bodegas', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.RemoveField(
            model_name='bodegas',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='bodegagenericos',
            name='categoria',
            field=models.CharField(choices=[('riester', 'Riester'), ('genericos', 'Genericos'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='bodegaotrasmarcas',
            name='categoria',
            field=models.CharField(choices=[('riester', 'Riester'), ('genericos', 'Genericos'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='bodegariester',
            name='categoria',
            field=models.CharField(choices=[('riester', 'Riester'), ('genericos', 'Genericos'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='bodegas',
            name='categoria',
            field=models.CharField(choices=[('riester', 'Riester'), ('genericos', 'Genericos'), ('otras marcas', 'Otras Marcas')], max_length=18, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='autor',
            field=models.ForeignKey(default='auth.User', max_length=400, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
