# Generated by Django 3.0.8 on 2020-07-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_auto_20200715_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='por',
        ),
    ]
