# Generated by Django 3.0.8 on 2020-07-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_auto_20200715_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salida',
            options={'ordering': ['id'], 'verbose_name': 'Salidas', 'verbose_name_plural': 'Salidas'},
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='autor',
            new_name='responsable',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Producto')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.Salida')),
            ],
            options={
                'verbose_name': 'Detalle de Salida',
                'verbose_name_plural': 'Detalle de Salidas',
                'ordering': ['id'],
            },
        ),
    ]
