# Generated by Django 3.0.8 on 2020-07-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_salida_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='final',
        ),
    ]
