# Generated by Django 3.0.8 on 2020-07-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0008_remove_producto_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
